insert into classifications (name, description, slug, state, published_edition_count, published_policies_count, `type`) values
('Economic Growth', 'The government has 4 aims to help the economy to grow: to create the most competitive tax system in the G20; to make the UK the best place in Europe to start, finance and grow a business; to encourage investment and exports as a route to a more balanced economy; and to create a more educated workforce that is the most flexible in Europe.

The government has 4 aims to help the economy to grow: to create the most competitive tax system in the G20; to make the UK the best place in Europe to start, finance and grow a business; to encourage investment and exports as a route to a more balanced economy; and to create a more educated workforce that is the most flexible in Europe.', 'economic-growth', 'published', 1, 1, 'Topic'),
('Housing', 'The government is helping local councils and developers work with local communities to plan and build better places to live for everyone. This includes building affordable housing, improving the quality of rented housing, helping more people to buy a home, and providing housing support for vulnerable people.', 'housing', 'published', 1, 1, 'Topic'),
('Climate Change', 'The government is working at home and abroad to adapt to the effects of climate change and reduce greenhouse gas emissions by investing in low-carbon energy sources, improving fuel standards in cars and increasing energy efficiency wherever possible.', 'climate-change', 'published', 1, 1, 'Topic'),
('Community and Society', 'The government is working to help people take action to solve their own problems and create strong, attractive and thriving neighbourhoods.', 'community-and-society', 'published', 1, 1, 'Topic'),
('Environment', 'The government is working to protect our environment by reducing pollution, reducing the amount of waste sent to landfill, protecting areas of parkland and wildlife reserves, and enforcing regulations that keep our water and air clean. We also help communities avoid or recover from flooding and other weather-related hazards.', 'environment', 'published', 1, 1, 'Topic'),
('Local Government', 'The government is giving local councils more power to decide how to spend public money in their areas so they can meet local peoples needs. At the same time, the government is helping to make sure Council Tax payers get value for money by making councils more transparent and accountable.', 'local-government', 'published', 1, 1, 'Topic'),
('National Security', 'The government works to identify the most pressing risks to our security, and put in place the ways and means to address them.', 'national-security', 'published', 1, 1, 'Topic'),
('Planning and Building', 'The government has simplified the planning system so councils have the freedom to make decisions in the best interests of their area. Councils and communities should be central to a system that achieves socially, environmentally and economically sustainable development.', 'planning-and-building', 'published', 1, 1, 'Topic'),
('Public Safety and Emergencies', 'The government provides funding and support for local emergency services including the police, fire and ambulance services, and sets national standards to make sure they are effective and consistent.', 'public-safety-and-emergencies', 'published', 1, 1, 'Topic'),
('Transport', 'Safe and dependable transport is essential to UK society and the economy. The government is working to make rail, road, air and water transport more efficient and effective, keep them safe and secure, and reduce greenhouse gas and other emissions. ', 'transport', 'published', 1, 1, 'Topic');
